### ISSUE TITLE
Problems 

### ISSUE THREAD

**Issue by gsrebro** [UiPath/Community.Activities#22]
Hi, Iwas using this Activity perfectly but when Uipath updated to last version, the automation I built stopped working.
The package version I'm using is 1.0.2.1 and the error is the copied below. Can you help me with this please?
Thanks!

Gabriel

"C:\Users\Bot PC\AppData\Local\UiPath\app-18.2.2\UiRobot
.exe" /file:"C:\Robot 1 - V1\Robot 1.xaml"
Robot 1 System.Xaml.XamlObjectWriterException: Cannot create unknown type '{clr-
namespace:GoogleSpreadsheet.Activities;assembly=GoogleSpreadsheet.Activities}Goo
gleSheetApplicationScope'.
   at System.Xaml.XamlObjectWriter.WriteStartObject(XamlType xamlType)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlW
riter, Boolean closeWriter)
   at System.Activities.XamlIntegration.FuncFactory`1.Evaluate()
   at System.Activities.DynamicActivity.OnInternalCacheMetadata(Boolean createEm
ptyBindings)
   at System.Activities.Activity.InternalCacheMetadata(Boolean createEmptyBindin
gs, IList`1& validationErrors)
   at System.Activities.ActivityUtilities.ProcessActivity(ChildActivity childAct
ivity, ChildActivity& nextActivity, Stack`1& activitiesRemaining, ActivityCallSt
ack parentChain, IList`1& validationErrors, ProcessActivityTreeOptions options,
ProcessActivityCallback callback)
   at System.Activities.ActivityUtilities.ProcessActivityTreeCore(ChildActivity
currentActivity, ActivityCallStack parentChain, ProcessActivityTreeOptions optio
ns, ProcessActivityCallback callback, IList`1& validationErrors)
   at System.Activities.ActivityUtilities.CacheRootMetadata(Activity activity, L
ocationReferenceEnvironment hostEnvironment, ProcessActivityTreeOptions options,
 ProcessActivityCallback callback, IList`1& validationErrors)
   at System.Activities.Hosting.WorkflowInstance.ValidateWorkflow(WorkflowInstan
ceExtensionManager extensionManager)
   at System.Activities.Hosting.WorkflowInstance.RegisterExtensionManager(Workfl
owInstanceExtensionManager extensionManager)
   at System.Activities.WorkflowApplication.EnsureInitialized()
   at System.Activities.WorkflowApplication.Enqueue(InstanceOperation operation,
 Boolean push)
   at System.Activities.WorkflowApplication.SimpleOperationAsyncResult.Run(TimeS
pan timeout)
   at System.Activities.WorkflowApplication.BeginRun(AsyncCallback callback, Obj
ect state)

**Comment by qbrandon** [comment]
1. it looks like the GoogleSpreadsheet package is not deployed
2. this may be due to the fact that we do not support executing jobs through the command line

Please publish your package locally and try running it from either Studio or the Robot tray / process list.

**Comment by gsrebro** [comment]
When I execute it from Studio it works and the package in installed from studio menu. I there a different way to install it in order to test if this works? Thanks!

**Comment by anevrekar** [comment]
I am facing the same issue using UiPathTeam.GoogleSpreadsheet.Activities package version 1.0.2.1. While this works when running the workflow from Studio, it does not work when the workflow is triggered from the Orchestrator at https://demo.uipath.com/.
Studio and Robot version is 2018.2.3 Enterprise edition.
Following is the errormessage in a prompt when running from Orchestrator
“Cannot create unknown type’{clr-namespace:GoogleSpreadsheet.Activities;assembly=GoogleSpreadsheet.Activities}'GoogleSheetApplicationScope”.

**Comment by lucaslima001** [comment]
Same here... Cannot create unknown type '{clr-namespace:UiPath.Excel.Activities.Business;assembly=UiPath.Excel.Activities}SequenceX'.

But focuses in excel.
While using at studio, it works fines.. trying use at orchestra and this error appear

**Comment by viogroza** [comment]
The issue no longer applicable since Google spreasheet activities and Excel activities are not in this repo
See https://docs.uipath.com/activities/other/latest/productivity/about-google-gsuite-activities
and https://docs.uipath.com/activities/other/latest/productivity/about-the-excel-activities-pack
