### ISSUE TITLE
Java Scope: Error intializing Java : System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by wixdonkey** [UiPath/Community.Activities#51]
**Describe the bug**

Java Scope: Error intializing Java : System.NullReferenceException: Object reference not set to an instance of an object.

**To Reproduce**
1. Download the java example from https://activities.uipath.com/docs/running-static-and-object-methods
2. Open the example without any problem by UiPath Studio Community Edition. 
3. Press 'Run' button, then raise the error as follow:
======================================================
19.7.0+Branch.master.Sha.8c253d13718eed5c7db27daef6facd1fe1b0d067

Source: Java Scope

Message: Error intializing Java : System.NullReferenceException: Object reference not set to an instance of an object.
   at UiPath.Java.Service.JavaService.<StartServiceAsync>b__7_2(IAsyncResult ar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.Service.JavaService.<StartServiceAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.JavaInvoker.<StartJavaService>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.Activities.JavaScope.<ExecuteAsync>d__12.MoveNext()

Exception Type: System.InvalidOperationException

RemoteException wrapping System.InvalidOperationException: Error intializing Java : System.NullReferenceException: Object reference not set to an instance of an object.
   at UiPath.Java.Service.JavaService.<StartServiceAsync>b__7_2(IAsyncResult ar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.Service.JavaService.<StartServiceAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.JavaInvoker.<StartJavaService>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.Activities.JavaScope.<ExecuteAsync>d__12.MoveNext() 
   at UiPath.Shared.Activities.AsyncTaskNativeImplementation.BookmarkResumptionCallback(NativeActivityContext context, Object value)
   at UiPath.Shared.Activities.AsyncTaskNativeActivity.BookmarkResumptionCallback(NativeActivityContext context, Bookmark bookmark, Object value)
   at System.Activities.Runtime.BookmarkCallbackWrapper.Invoke(NativeActivityContext context, Bookmark bookmark, Object value)
   at System.Activities.Runtime.BookmarkWorkItem.Execute(ActivityExecutor executor, BookmarkManager bookmarkManager)
==========================================================

**Expected behavior**
Could popup the messagebox as the expectation. 

**Screenshots**
![1](https://user-images.githubusercontent.com/10431159/61618212-ed721e00-ac9e-11e9-94f6-ad3e1bdef209.png)
![2](https://user-images.githubusercontent.com/10431159/61618323-2f02c900-ac9f-11e9-8416-ce3560e1aa27.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - UiPath.Java.Activities 1.0.7053.27728
 - 2019.7.0 - 7/16/2019 Community Edition
 - java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

**Additional context**
Download the example from below:
https://activities.uipath.com/docs/running-static-and-object-methods

**Comment by cosmyo** [comment]
Hi @wixdonkey I will take a look.
Meanwhile, have you tried setting Java Library Path in Java Scope to point to java.exe on your computer ?

**Comment by wixdonkey** [comment]
Here is my java home env:
![image](https://user-images.githubusercontent.com/10431159/62852943-7bc94500-bd1d-11e9-923a-9ae47e1af05c.png)

The java scope activity guide wrote:
Java Library Path - The path to the Java Library Executable java.exe file. If no path is supplied in this property, the Java Library will be loaded from the PATH environment variable. This field supports only strings and String variables.
https://docs.uipath.com/activities/docs/java-scope

Here is my scenario:
1. Only drag the 'Java Scope' to the stage.
2. Set the 'Java Library Path'.
![image](https://user-images.githubusercontent.com/10431159/62853441-f5156780-bd1e-11e9-9abb-cd0afde98050.png)
3. Press F5
A moment later the error would be raised.
![image](https://user-images.githubusercontent.com/10431159/62853522-3443b880-bd1f-11e9-8900-6fdc351a5c77.png)

**Comment by viogroza** [comment]
issue should be fixed in uipath.java.activities 2.1.1
